module.exports = [
  'Regrese por segunda vez y el servicio sigue igual de bueno. La calidad de su madera me trajo de vuelta.',
  'Volvi a comprar aqui porque la primera vez quede muy satisfecho. No decepciona.',
  'Ya es mi segunda compra en Madereria La Jardin y sigue siendo mi lugar favorito para madera en Tijuana.',
  'Regrese porque la madera de mi primera compra fue excelente. No busco en otro lado.',
  'Segunda visita y el precio sigue siendo el mejor de la zona. Los recomiendo sin dudar.',
  'Volvi por mas material y como siempre me atendieron rapido y con buen trato.',
  'Ya llevo dos compras aqui y en ambas el material llego perfecto. Muy confiable.',
  'Regrese porque el triplay que compre la primera vez era de muy buena calidad.',
  'Segunda compra y sigo igual de satisfecho. El servicio es consistente y eso vale mucho.',
  'Volvi a surtirme aqui. El precio y la calidad me convencieron de regresar.',
  'Ya es mi segundo pedido y todo llego en perfectas condiciones. Muy recomendados.',
  'Regrese por los barrotes 2x4 que necesitaba. Como siempre, buen precio y buena madera.',
  'Segunda vez que compro aqui y el personal sigue siendo amable y servicial.',
  'Volvi porque confio en su calidad. Para madera en Tijuana este es mi lugar.',
  'Ya son dos compras y nunca me han fallado. Proveedor confiable para mis proyectos.',
  'Regrese a surtirme de triplay y como siempre excelente atencion y buen material.',
  'Segunda visita al negocio y sigo impresionado con el surtido que manejan.',
  'Volvi por mas tablones y el precio sigue siendo competitivo. Los recomiendo.',
  'Ya llevo dos proyectos con su madera y ambos quedaron muy bien. Gracias.',
  'Regrese porque la primera experiencia fue tan buena que no quise buscar otro lugar.',
  'Segunda compra en La Jardin. El material es consistente en calidad siempre.',
  'Volvi porque el precio de su madera no lo encuentro igual en otro lado de Tijuana.',
  'Ya son dos visitas y en las dos me han atendido excelente. Muy recomendado.',
  'Regrese por material para otro proyecto. Como siempre rapidos y con buen stock.',
  'Segunda vez aqui y sigo siendo cliente feliz. La madera es de primera calidad.',
  'Volvi a comprar polín 4x4 y como la primera vez todo perfecto. Gran servicio.',
  'Ya llevo dos compras y el trato siempre es amable. Se nota que valoran al cliente.',
  'Regrese porque la calidad de su madera supero mis expectativas la primera vez.',
  'Segunda visita y el negocio sigue igual de surtido y bien atendido. Excelente.',
  'Volvi por cubiertas y como siempre buen precio y entrega inmediata. Gracias.',
  'Ya son dos pedidos y los dos llegaron completos y en buen estado. Muy confiables.',
  'Regrese a comprar mas triplay. El de la primera compra aguanto perfecto la obra.',
  'Segunda vez que vengo y no sera la ultima. Este lugar tiene todo lo que necesito.',
  'Volvi porque el shingle que compre la primera vez era de muy buena calidad.',
  'Ya llevo dos compras y el precio siempre es justo. Sin sorpresas al pagar.',
  'Regrese por recomendacion propia, ya que la primera experiencia fue excelente.',
  'Segunda compra y el servicio sigue siendo rapido y sin complicaciones. Perfecto.',
  'Volvi a surtirme de madera para otro proyecto. No me arrepiento de regresar.',
  'Ya son dos visitas y en ambas el material fue de la calidad que esperaba.',
  'Regrese porque aqui encuentro todo en un solo lugar. No necesito ir a otro lado.',
  'Segunda vez comprando OSB y sigue siendo el mejor precio que encuentro.',
  'Volvi porque el personal me oriento muy bien la primera vez. Servicio de calidad.',
  'Ya llevo dos proyectos con su cimbra fenolica y en ambos funciono perfecto.',
  'Regrese a comprar mas barrotes. La madera de mi primera compra era excelente.',
  'Segunda visita y sigo encontrando stock de lo que necesito. Muy bien abastecidos.',
  'Volvi porque la relacion calidad precio es la mejor que encontre en Tijuana.',
  'Ya son dos compras y el personal siempre me recibe con buena actitud. Gracias.',
  'Regrese por la membrana azul que necesitaba. Como siempre buen precio y calidad.',
  'Segunda vez aqui y todo sigue igual de bueno. Negocio confiable y serio.',
  'Volvi a comprar tablones y el material sigue siendo de primera. Muy satisfecho.',
  'Ya llevo dos pedidos grandes y en los dos me cumplieron sin problema. Excelentes.',
  'Regrese porque la primera compra fue perfecta y no tengo razon para cambiar.',
  'Segunda compra en La Jardin TJ. Los recomiendo para cualquier proyecto de madera.',
  'Volvi por mas material para mi obra. Como siempre, atencion rapida y precio justo.',
  'Ya son dos visitas y nunca he tenido que regresar material por defectos. Calidad.',
  'Regrese porque el triplay ranurado que compre aqui es el mejor de la zona.',
  'Segunda vez comprando y el proceso sigue siendo facil y rapido. Sin burocracia.',
  'Volvi a comprar porque confio en la calidad de su material. No falla nunca.',
  'Ya llevo dos proyectos terminados con su madera y los dos quedaron excelentes.',
  'Regrese por vigas y como siempre el precio es competitivo y el material bueno.',
  'Segunda visita al negocio. El trato es igual de amable que la primera vez.',
  'Volvi porque aqui siempre tienen lo que busco. Surtido completo en todo momento.',
  'Ya son dos compras y en ambas me ayudaron a cargar sin cobrar extra. Gracias.',
  'Regrese a comprar mas material para ampliacion. La primera compra fue perfecta.',
  'Segunda vez aqui y sigo impresionado con la atencion y la calidad del producto.',
  'Volvi porque el OSB que compre aqui tiene la mejor calidad que he encontrado.',
  'Ya llevo dos compras y el precio siempre ha sido honesto. Sin letra chica.',
  'Regrese por mas barrotes para terminar mi proyecto. Siempre tienen stock.',
  'Segunda compra y el servicio sigue siendo de primera. Los recomiendo mucho.',
  'Volvi a comprar triplay para mi cocina. El de la primera compra quedo perfecto.',
  'Ya son dos visitas y en las dos encontre lo que necesitaba sin buscar en otro lado.',
  'Regrese porque el personal me trato muy bien la primera vez. Volveria siempre.',
  'Segunda vez comprando aqui y sigo siendo cliente satisfecho. Calidad constante.',
  'Volvi por material de cubierta y como siempre buen precio y entrega inmediata.',
  'Ya llevo dos pedidos y en los dos el material llego en perfectas condiciones.',
  'Regrese porque la primera experiencia supero lo que esperaba. Muy recomendado.',
  'Segunda visita y el negocio sigue igual de ordenado y bien surtido. Excelente.',
  'Volvi a comprar polín para otro proyecto. El precio sigue siendo el mejor.',
  'Ya son dos compras y el trato siempre es respetuoso y rapido. Muy buen negocio.',
  'Regrese porque la madera de aqui dura mas que la que compre en otros lugares.',
  'Segunda vez aqui y como siempre encuentro todo lo que necesito para mi obra.',
  'Volvi por tablones 2x6 y el material sigue siendo recto y sin defectos.',
  'Ya llevo dos proyectos completados con su madera. Los dos quedaron muy bien.',
  'Regrese porque confio en su surtido y en que siempre hay stock disponible.',
  'Segunda compra en La Jardin. Sin duda el mejor lugar para madera en Tijuana.',
  'Volvi porque el precio de mayoreo que me dieron la primera vez fue excelente.',
  'Ya son dos visitas y en ambas el personal me oriento muy bien. Muy profesionales.',
  'Regrese a surtirme para otra obra. Como siempre atencion rapida y sin esperas.',
  'Segunda vez comprando y sigo encontrando los mejores precios de la zona.',
  'Volvi porque la cimbra que compre aqui aguanto mucho mas de lo esperado.',
  'Ya llevo dos compras y nunca me han dado material en mal estado. Muy confiables.',
  'Regrese por shingle para otro techo. La primera compra resulto de muy buena calidad.',
  'Segunda visita y el negocio sigue siendo mi primera opcion para madera en Tijuana.',
  'Volvi a comprar porque el servicio es consistente. Eso no tiene precio.',
  'Ya son dos pedidos y en los dos me trataron como cliente frecuente desde el inicio.',
  'Regrese porque aqui encuentro calidad y precio en un mismo lugar. Insuperable.',
  'Segunda compra en La Jardin TJ. Negocio serio que se gana la lealtad del cliente.',
  'Volvi porque la primera experiencia fue tan buena que no necesito buscar mas.',
  'Ya llevo dos compras y cada vez que vengo salgo mas satisfecho. Los recomiendo.'
];
