module.exports = [
  'Excelente madereria en Tijuana. Buen precio, madera de calidad y atencion rapida. Los recomiendo.',
  'Fui a comprar triplay y quede muy satisfecho. Buena variedad y precios accesibles. Regreso seguro.',
  'Muy buen servicio. Me ayudaron a encontrar lo que necesitaba para mi construccion. Gracias.',
  'Llevo tiempo comprando aqui y siempre me tratan bien. La madera es de buena calidad.',
  'Rapidos y amables. Encontre los 2x4 que necesitaba a buen precio. Muy recomendados.',
  'Primera vez que vengo y no sera la ultima. Buen surtido y precio justo.',
  'Gran variedad de madera y materiales. El personal conoce el producto y te orienta bien.',
  'Compre cubiertas y triplay, todo en buen estado. El precio es competitivo en la zona.',
  'Muy buena atencion desde que llegue. Me ayudaron a cargar el material sin cobrar extra.',
  'Siempre que necesito madera vengo aqui. Precios honestos y buena calidad.',
  'Buen lugar para comprar material de construccion en Tijuana. Los recomiendo con confianza.',
  'Compre para un proyecto grande y me cumplieron en cantidad y calidad. Gracias equipo.',
  'Me surtieron rapido y sin complicaciones. El material llego en perfectas condiciones.',
  'Excelente experiencia de compra. Personal amable y precios accesibles. Volveria sin dudar.',
  'Tienen todo lo que uno busca: surtido completo, buen precio y trato amable.',
  'Muy satisfecho con mi compra. La madera era justo lo que necesitaba y a buen precio.',
  'Rapida atencion y buen producto. Para proyectos de construccion son mi primera opcion.',
  'Me recomendaron este lugar y no me decepciono. Calidad y precio van de la mano aqui.',
  'Buen ambiente, personal servicial y precios que no encontre mejores en Tijuana.',
  'Aqui encontre lo que en otros lados no tenian. Buen surtido y los mejores precios.',
  'Los precios son muy razonables para la calidad que ofrecen. Los volvere a visitar.',
  'Encontre el triplay mas accesible de la zona sin sacrificar calidad. Muy contento.',
  'Me dieron un buen precio por volumen. Excelente para proyectos grandes.',
  'El precio que me cotizaron fue el mismo que pague. Sin sorpresas desagradables.',
  'Mejores precios que en las ferreterias de la zona. Recomendado al cien por ciento.',
  'Madera de primera calidad. Se nota la diferencia al trabajarla. Muy recomendados.',
  'El triplay no se pandea ni se humedece facil. Muy buena calidad de material.',
  'La madera esta bien seca y sin nudos problematicos. Excelente para construccion.',
  'Material resistente que aguanta bien la intemperie. Recomendado para exteriores.',
  'Las vigas son rectas y sin defectos. Calidad consistente en todos los pedidos.',
  'El personal me atendio desde que llegue. Sin esperar ni hacer fila.',
  'Atencion rapida y eficiente. Valoran el tiempo del cliente. Muy bien.',
  'Me explicaron las diferencias entre materiales sin presionarme a comprar.',
  'Muy amables con los clientes nuevos. Me senti bienvenido desde que entre.',
  'El personal conoce bien sus productos. Te orientan para elegir lo correcto.',
  'Servicio profesional de principio a fin. Muy satisfecho con la atencion.',
  'Me ayudaron a cargar sin que lo pidiera. Servicio que va mas alla.',
  'Responden las preguntas sin rodeos. Informacion directa y util siempre.',
  'El trato es amable con todos, ya sea que compres mucho o poco. Excelente.',
  'Servicio que inspira confianza desde la primera compra. Volvere seguro.',
  'Compre barrotes 2x4 de 8 pies y son perfectos para mi construccion.',
  'El triplay de 1/2 que compre es ideal para mis muebles. Muy recomendado.',
  'Los tablones 2x6 son rectos y de buen peso. Excelente material para obra.',
  'Las vigas 4x4 son bien cuadradas y sin nudos grandes. Perfectas para estructura.',
  'El triplay 3/4 para mi piso quedo perfecto. Excelente material de calidad.',
  'El OSB Cimbraplay es resistente y facil de cortar. Muy practico para usar.',
  'El shingle asfaltico instalo facil y quedo bien sellado. Material recomendado.',
  'La membrana azul que compre no ha tenido goteras. Excelente producto.',
  'Los barrotes de 16 pies son rectos sin curvaturas. Muy buenos para construccion.',
  'El material para mi techo llego en tiempo y forma. Sin defectos de fabrica.',
  'Construi una habitacion con su madera y quedo muy bien. Material de calidad.',
  'Remodelé mi cocina con su triplay. El resultado es excelente. Muy contento.',
  'Hice una bodega con sus materiales y quedo solida y bien terminada. Gracias.',
  'Para cerco de madera, los tablones que venden son los mejores que encontre.',
  'Construi un deck en mi jardin con su madera. Quedo increible. Recomendado.',
  'Hice muebles con su triplay y la calidad es notable. Clientes muy felices.',
  'Mi proyecto de ampliacion quedo impecable gracias a sus materiales de calidad.',
  'Los recomiendo a todos mis conocidos que necesitan madera en Tijuana.',
  'Ya le conte a varios colegas contratistas. Aqui compro siempre sin dudar.',
  'Los recomiendo sin pensarlo dos veces. El mejor lugar de madera en Tijuana.',
  'Mande a mi cunado y tambien quedo contento. Confiable para todos.',
  'Mi empresa compra aqui desde hace tiempo. Siempre cumplen sin falla.',
  'Los recomiendo a cualquier constructor en Tijuana. Sin ningun tipo de duda.',
  'Soy cliente desde hace anos y no tengo queja alguna. Siempre igual de buenos.',
  'Vuelvo cada vez que tengo un proyecto nuevo. Nunca me han fallado.',
  'Llevo mas de diez proyectos comprando aqui. Siempre confiable y puntual.',
  'Compro cada mes y siempre hay stock de lo que necesito. Muy confiable.',
  'No importa que tanto compre, siempre me tratan igual de bien. Gracias.',
  'Pedido tras pedido, nunca me han defraudado. Eso no tiene precio.',
  'Soy cliente frecuente y me hacen sentir valorado. Muy buen trato siempre.',
  'Nunca he tenido que regresar material por defectos. Calidad garantizada.',
  'Me atendieron super rapido, estaba de prisa y lo notaron. Muy atentos.',
  'En menos de quince minutos ya tenia mi material cargado. Rapidisimos.',
  'Sin fila, sin espera larga. Llegue, pedi, pague y listo. Muy eficientes.',
  'Atienden rapido incluso cuando hay varios clientes. Muy bien organizados.',
  'Proceso de compra sin burocracia. Directo y sin complicaciones innecesarias.',
  'La mejor madereria de Col. Jardin y de muchas colonias mas en Tijuana.',
  'Tijuana necesita negocios asi. Profesionales y accesibles al mismo tiempo.',
  'En Tijuana son los mejores. Los locales sabemos bien donde comprar madera.',
  'Negocio local que le gana a las cadenas en precio y servicio. Excelentes.',
  'De los pocos lugares donde sientes que te tratan como cliente, no como numero.',
  'Compre madera para una remodelacion de bano y el resultado fue increible.',
  'Para techos y cobertizos, su material es el mas confiable que he usado.',
  'Para muros divisorios el triplay es ideal. Material perfecto para ese uso.',
  'Construi escaleras de madera con sus tablones. Estan firmes despues de anos.',
  'La cubierta de mi local comercial se hizo con su material. Sin filtraciones.',
  'No perdi tiempo buscando en otras madererias. Vine directo aqui y acerte.',
  'Encontre en un solo viaje todo lo que buscaba para mi proyecto de obra.',
  'Sin vueltas ni perdida de tiempo. Aqui esta todo lo que necesitas siempre.',
  'Me ahorraron dos dias de busqueda. Tienen surtido completo en todo momento.',
  'Una sola visita fue suficiente para surtir todo el material de mi obra.',
  'Excelente para compras de mayoreo. Manejan bien los pedidos mas grandes.',
  'Para constructores independientes este es el mejor aliado de madera.',
  'Mi cuadrilla compra aqui siempre. Buenos precios para trabajo constante.',
  'Para obras largas de varios meses siempre tienen disponibilidad de stock.',
  'Para mejorar el hogar en Tijuana, esta madereria no tiene competencia.',
  'Compre para mi primera construccion y aprendi el valor de buen material.',
  'El encargado me explico que materiales usar para cada parte de la obra.',
  'Para alguien que no sabe de madera, el personal es de gran ayuda aqui.',
  'Encontre lo que buscaba aunque no sabia exactamente como pedirlo. Gracias.',
  'Cinco estrellas bien merecidas. Los de la zona ya los conocemos y respetamos.'
];
